### ISSUE TITLE
Pseudorange access

### ISSUE THREAD

**Issue by superjax** [inertialsense/InertialSenseSDK#3]
I'm trying to expose psuedorange measurements, but I am not able to find them in the SDK.  Maybe I'm just an idiot, but I can't seem to find it in `data_sets.h`.

Which data identifier should I be looking at for the pseudoranges?  I've found the `cno` values in the `sat_info_t` structs, but I was under the impression that pseudoranges were different from the noise ratio.

Thanks, sorry if I'm just overlooking something stupid.

**Comment by waltjohnson** [comment]
Let me look into this.  I'll get back with you!

*Walt Johnson | CEO & Founder* | *Inertial Sense, LLC*

72 North 720 East | Salem, UT 84653

Office: 801-610-6359 | Mobile: 801-380-0819 | InertialSense.com
<http://www.inertialsense.com/>



Electronic Privacy Notice. This e-mail, and any attachments, contains
information that is, or may be, covered by electronic communications
privacy laws, and is also confidential and proprietary in nature.
Information contained in or attached to this email may be subject to export
controls, may be privileged, and is confidential and competition sensitive.
If you are not the intended recipient, please delete this email and notify
me immediately. You are not authorized to copy or use this email for any
purpose. If you are not the intended recipient, please be advised that you
are legally prohibited from retaining, using, copying, distributing, or
otherwise disclosing this information in any manner. Instead, please reply
to the sender that you have received this communication in error, and then
immediately delete it. Thank you in advance for your cooperation.
